name: GitHub Actions Demo
on:
  push:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: python -m unittest test_adition.py
  SSH-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploiement de addition.py
        env:
          SSH_ADDRESS: ${{ secrets.SSH_ADDRESS }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sudo apt-get install -y sshpass
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no addition.py "$SSH_ADDRESS":~/TR/addition.py